service: part of the reload command is now also generation of the supervisor config file using prepare_default_config.sh script.

diff --git a/configs/prepare_default_config.sh.in b/configs/prepare_default_config.sh.in
--- a/configs/prepare_default_config.sh.in
+++ b/configs/prepare_default_config.sh.in
@@ -96,6 +96,7 @@ if [ "$1" = "configonly" ]; then
                 cat "$tmp_output_file" > "$output_file_path"
                 if [ $? -ne 0 ]; then
                         echo "Error: does not have write permissions to $output_file_path file"
+                        exit 1 # failure
                 fi
         fi
 
diff --git a/nemea-supervisor.in b/nemea-supervisor.in
--- a/nemea-supervisor.in
+++ b/nemea-supervisor.in
@@ -126,7 +126,10 @@ restart )
 	;;
 
 reload )
-        # TODO complete reload config
+	if [ `$BINDIR/prepare_default_config.sh configonly` != 0]; then
+		echo "Error: could not generate $CONFIG_FILE using $BINDIR/prepare_default_config.sh configonly"
+		exit 1
+	fi
 	$SUPERVISOR_CLI -r
         ;;
 
